apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain-task-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brain-task-app
  template:
    metadata:
      labels:
        app: brain-task-app
    spec:
      imagePullSecrets:
        - name: ecr-registry   # MUST be inside pod spec
      containers:
        - name: brain-task-app
          image: 838180512863.dkr.ecr.us-east-2.amazonaws.com/brain-task-app:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: brain-task-app-service
spec:
  type: LoadBalancer
  selector:
    app: brain-task-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
